### ISSUE TITLE
📝 Update README

### ISSUE THREAD

**Issue by calumjs** [SSWConsulting/SSW.Rules.GPT#100]
Cc:

Hi 

### Pain

Current README instructions are not sufficient to run project without having to call @jackreimers and have him sort it out for you

### Tasks

- [ ] Add appsettings template with placeholders
- [ ] Remove unnecessary launch settings profiles...or at least make sure it defaults to the right thing
- [ ] Add instructions to set up Multiple Startup Projects

### Acceptance Criteria

- [ ] Someone is able to follow the README and start the project without asking for help

Thanks!

**Comment by jackreimers** [comment]
Resolved by #109
