### ISSUE TITLE
✨ Add Chat History feature

### ISSUE THREAD

**Issue by jackreimers** [SSWConsulting/SSW.Rules.GPT#146]
Cc: @adamcogan @calumjs @leehawkinsssw @KahaMason @Levijj22 @BrookJeynes 

Hi 
  
From the email thread IMPORTANT SSW RulesGPT - encourage sign-in 🍀
Feature requested by @adamcogan

### Pain

Currently there is no way for users to save or access their messages past messages.

### Suggested Solution

Store the message history of signed in users and display each conversation in a collapsible side nav on the left of the page.

![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/10693364/d1d048e7-06c6-4343-97e9-3840e8395edf)
**Figure: ChatGPT style left nav conversation history**

### Acceptance Criteria

* Signed in users messages should be automatically save.  
* Saved messages are listed in a left side nav.
* Conversations can be opened, viewed and messages can be edited and resent as normal.
* Users can delete individual conversations or clear their whole history.
* Done email sent to Adam in email thread "IMPORTANT SSW RulesGPT - encourage sign-in 🍀"

Thanks!

```[tasklist]
### Tasks
- [ ] Store message history from signed in users
- [ ] Use the OpenAI API to get a title for the conversation
- [ ] Create a left side navigation component that displays the history
- [ ] Add delete and clear history functionality
```

**Comment by jackreimers** [comment]
As per my conversation with @calumjs we are going to validate the serialized chat history object from the frontend and then write it to the database.

**Comment by jackreimers** [comment]
Done - chat history is working as expected in production

**Comment by bradystroud** [comment]
Done video
https://youtu.be/ciadMFFQ9eg
