### ISSUE TITLE
♻️ Upgrade to GPT4o

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Rules.GPT#168]
Keep GPT 3.5 as the signed out model.

Change the signed in model from GPT 4 to GPTo (faster + cheaper)

```[tasklist]
### Tasks
- [ ] When you sign in you can use GPT 4o
- [ ] Consider refactoring code to make this easy - There will frequently be new models released, and we should make it as easy as possible to update RulesGPT to support them
- [ ] Alternatively, document the process so the changes are easy for next time
```

**Comment by jernejk** [comment]
@bradystroud, can we add GPT-4o-mini, o1 and o1-mini as well?
