### ISSUE TITLE
💄 Header - Keep it consistent with SSW.Rules

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Rules.GPT#75]
Cc: @adamcogan @jaydenalchin @tiagov8 

Hi @jackreimers ,
  
As per my conversation with @adamcogan @jaydenalchin @tiagov8 the header should be more consistent with SSW.Rules.

```[tasklist]
### Tasks
- [x] Remove vertical bar
- [x] Remove link from “powered by” text
- [x] Make light mode header light (To be consistent with dark mode)
- [x] Make tagline position consistent
- [x] Make tagline casing consistent
- [ ] Get changes checked by Jayden and Tiago, then Adam
```

![](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/38869720/7e92a6b1-e9d1-4e8c-9c5d-8792fdd1e500)
**Figure: Rules logo design**

Thanks!

**Comment by jackreimers** [comment]
As per my conversation with Adam and Brady, we are going to leave the design as is except for changing the suggested questions to lowercase.
