### ISSUE TITLE
✨ Add installation instructions for RulesGPT on various devices

### ISSUE THREAD

**Issue by jernejk** [SSWConsulting/SSW.Rules.GPT#83]
Cc: @adamcogan 
Hi,

SSW heavily relies on rules and such it would be great if we show people how to install RulesGPT to be more accessible.

On Edge:
1. `...` 
2. `Apps` 
3. `Install this site as an app`

On iPad (Safari):
1. Share button
2. Add to Home Screen
3. Add

On iPhone:
1. Download the app: https://apps.apple.com/us/app/chatgpt/id6448311069

On Android:
1. ...
2. Add to Home screen
3. Add

**NOTE**: Yes, the difference between iOS and Android is the casing of "Screen".🤔
  
### Pain
Users may not know how to install RulesGPT for easier access on their devices.

### Suggested Solution
Add instructions for installing RulesGPT on Edge, iPad, iPhone, and Android devices.

### Tasks

- [ ]  Create a dedicated page or section for RulesGPT installation instructions 📝
- [ ] Add instructions for installing RulesGPT on:
	- [ ] Edge browser (Windows) 🧑‍💻🪟
	- [ ] Safari (Mac) 🧑‍💻🍏
	- [ ] iPad (Safari) 💻🍏
	- [ ] iPhone (App Store link) 📱🍏
	- [ ] Android devices 📱🤖

### Acceptance Criteria
1. Users can easily find and follow the installation instructions for their device 📲
2. The instructions are clear, concise, and accurate 🎯
3. Let's user know only certain combination of OS and browser works 🌐

### Screenshots
![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/5943653/4a0664c0-d685-458d-ae65-0953b8e2a725)
**Figure:** We can install the app by going `...` | `Apps` | `Install this site as an app`.

![image](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/5943653/19759421-d050-48d3-a3a0-e56ecaa0d091)
**Figure:** RulesGPT is easier to access via taskbar as a separate app.

Thanks!

**Comment by jackreimers** [comment]
@jernejk is there a reason we are including a link to the OpenAI app for iPhone users? 
RulesGPT can be installed as an app on an iPhone the same as on an iPad

**Comment by jernejk** [comment]
Ah, nevermind, just c&p iPad instructions. Mixing up ChatGPT and RulesGPT instructions :)
