### ISSUE TITLE
🔎 SEO - Make it googleable

### ISSUE THREAD

**Issue by bradystroud** [SSWConsulting/SSW.Rules.GPT#85]
Cc: @MattParkerDev @jackreimers

Hi Team,
  
### Pain
Its not googlable

![](https://github.com/SSWConsulting/SSW.Rules.GPT/assets/38869720/99a88cf7-f2d5-4a44-884f-423a437392e1)
**Figure: Cant find it 🤷🏻‍♂️**

### Suggested Solution
Improve SEO
This is hard because its a WASM page.

@Hona wrote about how to make it work https://lukeparker.dev/blog/blazor-wasm-seo
Thanks @Hona 

### Tasks
- [ ] Follow Luke's blog
- [ ] Ask him for help if needed
- [ ] Ensure Google is indexing it

Thanks!
